### ISSUE TITLE
store 

### ISSUE THREAD

**Issue by triggan503** [junhuang21484/Apple-Instore-Monitor#2]
store near you as in the store ID?

**Comment by junhuang21484** [comment]
yes, the store id that you want to monitor and it will automatically search for stores near that store id as well. I believe if you leave it blank it will just find the stores near your IP running this program, but I have not done much testing regarding it yet.

**Comment by triggan503** [comment]
would it work if you code the store id in this format? "store_near": ["R0xx", "R0xx", "Rxx"],

**Comment by junhuang21484** [comment]
It only supports a single store id as the initial input right now, but it usually will find a handful of stores near that initial store id depending on where you are monitoring.

**Comment by triggan503** [comment]
Hmm no wonder I ran it and could not see a notification to my webhook

**Comment by junhuang21484** [comment]
Was everything working fine after you used a single store id?

**Comment by triggan503** [comment]
Yes it works.  Excited to
Get them to be added feature 😀

**Comment by triggan503** [comment]
Can the polling time be shortened from 5 to 1-3 seconds and the cooldown to 30?

**Comment by junhuang21484** [comment]
you can edit those to your need

**Comment by triggan503** [comment]
Exception in thread Thread-50:
Traceback (most recent call last):
  File "C:\Users\Triggan\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Triggan\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Triggan\AppData\Local\Programs\Python\Python39\lib\site-packages\win10toast\__init__.py", line 83, in _show_toast
    self.hwnd = CreateWindow(self.classAtom, "Taskbar", style,
AttributeError: 'ToastNotifier' object has no attribute 'classAtom'
[2021-10-13 13:05:25]: SKU (MLKR3LL/A) has stock been found
Exception in thread Thread-51:
Traceback (most recent call last):

getting this message.

**Comment by triggan503** [comment]
it also does not pick up on the store ID I input though that store has stock it would pick up store that are 200 miles away

**Comment by junhuang21484** [comment]
That error will be fixed in upcoming update. Regarding the store id, if you do not mind can you show me your store id? I have not encounter this error before

**Comment by triggan503** [comment]
R134
